# Generated by Django 4.2.26 on 2025-11-29 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('code', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('designation', models.CharField(blank=True, default='', max_length=255)),
                ('criticite', models.CharField(default='normal', max_length=16)),
                ('stock_actuel', models.FloatField(default=0)),
                ('stock_securite', models.FloatField(default=0)),
                ('moyenne_m3', models.FloatField(default=0)),
                ('prevision_m1', models.FloatField(default=0)),
                ('ecart_pourcent', models.FloatField(default=0)),
                ('prix_unitaire', models.FloatField(default=0)),
                ('fournisseur', models.CharField(blank=True, default='', max_length=255)),
                ('delai', models.FloatField(default=0)),
                ('n_ac_2025', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
            },
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('valeur', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.part')),
            ],
            options={
                'verbose_name': 'Consumption',
                'verbose_name_plural': 'Consumptions',
                'unique_together': {('part', 'date')},
            },
        ),
    ]
