# Generated by Django 4.2.26 on 2025-11-29 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_cap', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Budget configuration',
                'verbose_name_plural': 'Budget configuration',
            },
        ),
        migrations.AddField(
            model_name='part',
            name='approuve',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=False)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.part')),
            ],
            options={
                'verbose_name': 'Selection',
                'verbose_name_plural': 'Selections',
            },
        ),
    ]
