# Generated by Django 4.2.26 on 2025-11-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_budgetconfig_part_approuve_selection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.CharField(default='Système', max_length=128)),
                ('role', models.CharField(default='Auto', max_length=64)),
                ('action', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=64)),
                ('details', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
            },
        ),
    ]
