# Generated by Django 5.1.1 on 2025-11-05 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('critique', 'Critique'), ('warning', 'Warning'), ('info', 'Info')], max_length=20)),
                ('severity', models.CharField(default='moyenne', max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('details', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('elastic', 'Élastique'), ('rigid', 'Rigide'), ('hydraulic', 'Hydraulique'), ('chain', 'Chaîne'), ('magnetic', 'Magnétique')], max_length=20)),
                ('criticite', models.CharField(choices=[('urgent', 'Urgent'), ('moyen', 'Moyen'), ('normal', 'Normal')], default='normal', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lead_time_days', models.PositiveIntegerField(default=0)),
                ('stock_actuel', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('selected', models.BooleanField(default=False)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.part')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='portal.supplier'),
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('moyenne_m3', models.IntegerField(default=0)),
                ('prevision_m1', models.IntegerField(default=0)),
                ('ecart_pourcent', models.IntegerField(default=0)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='portal.part')),
            ],
            options={
                'unique_together': {('part', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='en_attente', max_length=20)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='portal.part')),
            ],
            options={
                'unique_together': {('part', 'month')},
            },
        ),
    ]
